
upstream_density: 0.9
downstream_density: 0.0

mean_scale: 0.7
sd_scale: 0.5
mean_threshold: 0.2
sd_threshold: 0.4
mean_decay: 0.4
sd_decay: 0.2

n: 2
kn: 0.5

mean_weight: 0.5
sd_weight: 0.2

cost_type: "parabolic"
mean_cost: 1.0
sd_cost: 0.0

mean_init_product: 0.2
sd_init_product: 0.25

mode: "aff" # random, aff, eff, alt
rect: "ReLU"
epistasis: "sum"


generator: "normal"

is_phene: True
